# http://module-build.sourceforge.net/META-spec.html
#
name:         WWW-Yahoo-Horoskop
version:      0.1
version_from: Horoskop.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
